name: asbru
version: '6.4.3'
base: core22
architectures:
  - build-on: amd64


  - build-on: arm64
    
       
summary: Asbru-CM Porting for snapcraft
description: 
      
      Asbru-CM Porting for snapcraft
      


confinement: strict

apps:
    asbru:
        command: bin/asbru-cm
        extensions: [gnome]
        slots:
            - dbus-asbru   
        environment:
            
              LANG: C.UTF-8
              LC_ALL: C.UTF-8
              PERL5LIB:  "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl-base:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl5/5.34:$SNAP/usr/share/perl5/:$SNAP/usr/share/perl/5.34:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.34:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.34"

      
        plugs: [ desktop, desktop-legacy, gsettings, opengl, wayland, x11, mount-observe, calendar-service, network, network-bind]

slots:
  dbus-asbru:
    interface: dbus
    bus: session
    name: org.asbru-cm.main
      
plugs:
    desktop:
        mount-host-font-cache: false
    gtk-3-themes:
        interface: content
        target: $SNAP/data-dir/themes
        default-provider: gtk-common-themes
    icon-themes:
        interface: content
        target: $SNAP/data-dir/icons
        default-provider: gtk-common-themes
    sound-themes:
        interface: content
        target: $SNAP/data-dir/sounds
        default-provider: gtk-common-themes
    gnome-42-2204:
        interface: content
        target: $SNAP/gnome-platform
        default-provider: gnome-42-2204
parts:

    
    dependencies:
        plugin: nil        
        stage-packages: [perl, libvte-2.91-0, xapp, libcairo-perl, libfindbin-libs-perl, libglib-perl, libpango-perl, libsocket6-perl, libexpect-perl, libnet-proxy-perl, libyaml-perl, libcrypt-cbc-perl, libcrypt-blowfish-perl, libgtk3-perl, libnet-arp-perl, libossp-uuid-perl, openssh-client, telnet, ftp, libcrypt-rijndael-perl, libxml-parser-perl, libcanberra-gtk-module, dbus-x11, libx11-guitest-perl, libgtk3-simplelist-perl, gir1.2-wnck-3.0, gir1.2-vte-2.91]

  
    sources:  
        
        plugin: dump
        source-type: git
        source: https://github.com/asbru-cm/asbru-cm.git
        organize:
          '*': bin/
